apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: brianrandellpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: brianrandellpipelinesjavascriptdocker 
    spec:
      containers:
        - name: brianrandellpipelinesjavascriptdocker 
          image: aksandadsenvacr.azurecr.io/brianrandellpipelinesjavascriptdocker
          ports:
          - containerPort: 8080